# Configuration des sources RSS pour la page Actualités de France Territoriale
# Thématiques disponibles :
#   Transitions | Numérique | Finances | Urbanisme / Aménagement
#   Action Sociale | Animer / Décider / Coopérer | Autre

sources:

  - name: CEREMA
    wiki_id: CeremA
    rss_urls:
      - https://www.cerema.fr/fr/rss/news/feed
      - https://doc.cerema.fr/Portal/Recherche/Search.svc/SearchRss?key=4517a4fa103f7f4b081f437a4830c82d&useSearchSort=false&useSearchResultSize=true
    thematiques:
      - Transitions
      - Urbanisme / Aménagement
      - Numérique

  - name: ADEME - Librairie
    wiki_id: LaLibrairieAdeme2
    rss_urls:
      - https://librairie.ademe.fr/rss/nouveautes.xml
      - https://librairie.ademe.fr/rss/actualites.xml
    thematiques:
      - Transitions
      - Numérique
      - Finances

  - name: Banque des Territoires
    wiki_id: RessourcesDeLaBanqueDesTerritoires
    rss_urls:
      - https://www.banquedesterritoires.fr/flux/localtis.xml
    thematiques:
      - Finances
      - Urbanisme / Aménagement
      - Transitions
